language: python

python:
  - '2.7'

cache: pip

install:
  - pip install -r requirements.txt
  - git clone --recurse-submodules https://github.com/web2py/web2py.git
  - cd web2py/applications; ln -s ../../. eve; cd ..

script: ./web2py.py --test eve/test

notifications:
  email: true
